name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        version:
          - '1.20'
          - '1.21'
          - '1.22'

    runs-on: ubuntu-latest

    # services:
    #   rabbitmq:
    #     image: rabbitmq:3.13.4-management
    #     env:
    #       RABBITMQ_DEFAULT_USER: guest
    #       RABBITMQ_DEFAULT_PASS: guest
    #       RABBITMQ_DEFAULT_VHOST: amqpextra
    #     ports:
    #       - 5672:5672
    #       - 15672:15672

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - name: unit-test
        env:
          NOMOCKGEN: 1
        run: make unit-test

      # - name: e2e-test
      #   run: make e2e-test
